# Lab02 Neural Network Tensor manipulation
202035513 Kim Ji Woo

In [76]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets

# GPU Setting
device = torch.device('mps:0' if torch.backends.mps.is_available() else 'cpu')
print(f"PyTorch version:{torch.__version__}") # 1.12.1 이상
print(f"MPS 장치를 지원하도록 build 되었는지: {torch.backends.mps.is_built()}") # True 여야 합니다.
print(f"MPS 장치가 사용 가능한지: {torch.backends.mps.is_available()}") # True 여야 합니다.

PyTorch version:1.13.1
MPS 장치를 지원하도록 build 되었는지: True
MPS 장치가 사용 가능한지: True


## Numpy review

## 1D Array with Numpy

In [77]:
import numpy as np
t = np.array ([0])

## Tensor in Python
### 1D Array with Pytorch

In [78]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [79]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [80]:
t = torch.FloatTensor([[1.,2.,3.,],[4.,5.,6.,],[7.,8.,9.],[10.,11.,12.]])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [81]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t[:,1])
print(t[:,1].size)
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
<built-in method size of Tensor object at 0x7fa2c2116980>
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [82]:
# Numpy array into torch
t = np.array([[[1.,2.,3.,],[4.,5.,6.,]],[[7.,8.,9.],[10.,11.,12.]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [83]:
# Above code is same as...
t2 = np.array([[[1.,2.,3.,],[4.,5.,6.,]],[[7.,8.,9.],[10.,11.,12.]]])
ft2 = torch.from_numpy(t2).float()
print(ft2.shape)

torch.Size([2, 2, 3])


## Broadcasting
Transform dimensions to allow calculations

In [84]:
# Same shape
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1 + m2)

tensor([5., 5.])


In [85]:
# Vector + scalar
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
print(m1)
print(m2)
print(m1+m2)

tensor([1., 2.])
tensor([3.])
tensor([4., 5.])


In [86]:
# 2x1 Vector + 1x2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1)
print(m2)
print(m1+m2)

tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


## Multiplication VS Matrix Multiplication

In [87]:
print("Mul vs Matmul")
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('shale of Matrix 1: ', m1.shape)
print('shale of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('shale of Matrix 1: ', m1.shape)
print('shale of Matrix 2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2))

Mul vs Matmul
shale of Matrix 1:  torch.Size([2, 2])
shale of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
shale of Matrix 1:  torch.Size([2, 2])
shale of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [88]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [89]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [90]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [91]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max, Argmax

In [92]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t.max())

tensor(4.)


max operator returns 2 values : maximum value and argmax (index 0f maximum value)

In [93]:
print(t.max(dim=0))
print('\nMax: ', t.max(dim=0)[0])
print('ArgMax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

Max:  tensor([3., 4.])
ArgMax:  tensor([1, 1])


In [95]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## Squeeze

In [94]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [96]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## UnSqueeze

In [97]:
ft = torch.Tensor([0,1,2,3])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqeeze(0))
print(ft.unsqeeze(0).shape)

# Example of View()
print()
print(ft.view(2,-1))
print(ft.view(2,-1).shape)