# Lab02 Neural Network Tensor manipulation
202035513 Kim Ji Woo

In [134]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets

# GPU Setting
device = torch.device('mps:0' if torch.backends.mps.is_available() else 'cpu')
print(f"PyTorch version:{torch.__version__}") # 1.12.1 이상
print(f"MPS 장치를 지원하도록 build 되었는지: {torch.backends.mps.is_built()}") # True 여야 합니다.
print(f"MPS 장치가 사용 가능한지: {torch.backends.mps.is_available()}") # True 여야 합니다.

PyTorch version:1.13.1
MPS 장치를 지원하도록 build 되었는지: True
MPS 장치가 사용 가능한지: True


## Numpy review

In [135]:
import numpy as np
t = np.array ([0])

## Tensor in Python
### 1D Array with Pytorch

In [136]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [137]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [138]:
t = torch.FloatTensor([[1.,2.,3.,],[4.,5.,6.,],[7.,8.,9.],[10.,11.,12.]])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [139]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t[:,1])
print(t[:,1].size)
print(t[:,:-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
<built-in method size of Tensor object at 0x7fa2b152cea0>
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [140]:
# Numpy array into torch
t = np.array([[[1.,2.,3.,],[4.,5.,6.,]],[[7.,8.,9.],[10.,11.,12.]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [141]:
# Above code is same as...
t2 = np.array([[[1.,2.,3.,],[4.,5.,6.,]],[[7.,8.,9.],[10.,11.,12.]]])
ft2 = torch.from_numpy(t2).float()
print(ft2.shape)

torch.Size([2, 2, 3])


## Broadcasting
Transform dimensions to allow calculations

In [142]:
# Same shape
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1 + m2)

tensor([5., 5.])


In [143]:
# Vector + scalar
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
print(m1)
print(m2)
print(m1+m2)

tensor([1., 2.])
tensor([3.])
tensor([4., 5.])


In [144]:
# 2x1 Vector + 1x2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1)
print(m2)
print(m1+m2)

tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


## Multiplication VS Matrix Multiplication

In [145]:
print("Mul vs Matmul")
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('shale of Matrix 1: ', m1.shape)
print('shale of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('shale of Matrix 1: ', m1.shape)
print('shale of Matrix 2: ', m2.shape)
print(m1 * m2)
print(m1.mul(m2))

Mul vs Matmul
shale of Matrix 1:  torch.Size([2, 2])
shale of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
shale of Matrix 1:  torch.Size([2, 2])
shale of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [146]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [147]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [148]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [149]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max, Argmax

In [150]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t.max())

tensor(4.)


max operator returns 2 values : maximum value and argmax (index 0f maximum value)

In [151]:
print(t.max(dim=0))
print('\nMax: ', t.max(dim=0)[0])
print('ArgMax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

Max:  tensor([3., 4.])
ArgMax:  tensor([1, 1])


In [152]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## Squeeze

In [153]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [154]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## UnSqueeze

In [155]:
ft = torch.Tensor([0,1,2,3])
print(ft.shape)

torch.Size([4])


In [156]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

# Example of View()
print(ft.view(2,-1))
print(ft.view(2,-1).shape)

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0., 1., 2., 3.]])
torch.Size([1, 4])
tensor([[0., 1.],
        [2., 3.]])
torch.Size([2, 2])
tensor([[0.],
        [1.],
        [2.],
        [3.]])
torch.Size([4, 1])


## Type Casting

In [157]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

print("\n------typecast:float------")
print(lt.float())

tensor([1, 2, 3, 4])

------typecast:float------
tensor([1., 2., 3., 4.])


In [158]:
btype = torch.ByteTensor([True,False,False,True])
print(btype)

print("\n------typecast:long------")
print(btype.long())
print("\n------typecast:float------")
print(btype.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)

------typecast:long------
tensor([1, 0, 0, 1])

------typecast:float------
tensor([1., 0., 0., 1.])


## Concatenate

In [162]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y], dim = 0))
print()
print(torch.cat([x,y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#Stacking

In [165]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0),z.unsqueeze(0)],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros